### ISSUE TITLE
playsound does not work with linux

### ISSUE THREAD

**Issue by mogoh** [Rotschnabel/TwitchTTS#2]
Error code:

```
Task exception was never retrieved
future: <Task finished name='Task-35' coro=<Bot.event_message() done, defined at twitch_tts.py:28> exception=ModuleNotFoundError("No module named 'gi'")>
Traceback (most recent call last):
  File "twitch_tts.py", line 31, in event_message
    speak(message.content)
  File "twitch_tts.py", line 15, in speak
    playsound.playsound(filename)
  File "/home/mogoh/.local/share/virtualenvs/TwitchTTS-TBwpSm26/lib/python3.8/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
ModuleNotFoundError: No module named 'gi'

```

**Comment by Rotschnabel** [comment]
playsound has been substituted by pydub
